import { atom } from "recoil";
import { IVassTrackingData } from "../../types/vassTracking.types";

export const vassTrackingState = atom<IVassTrackingData>({
  key: "vassTrackingState",
  default: {
    cust_nm: "",
    fare: "",
    pick_trade_cd: "",
    dv_tradesub_nm: "",
    dv_date: "",
    qa: "",
    relation_list: [
      {
        iv_type: "",
        iv_no_relation: "",
      },
    ],
    order_addres_doro: "",
    order_post_cd: "",
    pick_trade_nm: "",
    pick_tradesub_tel: "",
    level: "",
    total_fare: "",
    pick_tradesub_cd: "",
    dv_tradesub_cd: "",
    order_address_jibun: "",
    mount_fare: "",
    dv_nm: "",
    dv_tradesub_tel: "",
    iv_type: "",
    flight_fare: "",
    trace_list: [
      {
        tok_send: "",
        trade_cd: "",
        scan_time: "",
        scan_date: "",
        dv_time_nm: "",
        trade_nm: "",
        state_nm: "",
      },
    ],
    dv_tel: "",
    bigo: "",
    order_nm: "",
    dv_tel_hd: "",
    goods_nm: "",
    trust_nm: "",
    dv_img: "",
    dv_address_doro: "",
    order_tel_hd: "",
    dv_post_cd: "",
    pick_tradesub_nm: "",
    fare_type: "",
    flight_fare_type: "",
    result: "",
    dv_address_jibun: "",
    sign_img: "",
    pick_date: "",
    spout_trade_nm: "",
    add_fare: "",
    dv_trade_nm: "",
    island_fare: "",
    is_send: "",
    is_getInfo: "",
    consign_it: "",
    spout_trade_nm2: "",
    message: "",
    island_fare_type: "",
    order_date: "",
    dv_trade_cd: "",
    consign_nm: "",
    cust_cd: "",
  },
});
